runtime: python39
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: app.app

libraries:
- name: flask
  version: "0.12"
- name: werkzeug
  version: "2.2.1"
- name: gpxpy
  version: "1.5.0"
- name: geopy
  version: "2.2.0"